version: "3.9"

services:
  web-backend:
    image: web-backend-image
    deploy:
      replicas: 1
    networks:
      - glossary-network

  ml-service:
    build:
      context: ./ml_service
    container_name: ml-service
    ports:
      - "9000:9000"
    depends_on:
      - web-backend
    networks:
      - glossary-network

  web-frontend:
    build:
      context: ./GlossaryKEKACHY/frontend
    container_name: web-frontend
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - "8080:8080"
    depends_on:
      - web-backend
    networks:
      - glossary-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"
    networks:
      - glossary-network

  nginx:
    image: nginx:latest
    container_name: nginx-backend
    ports:
      - "80:80"  
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf 
    depends_on:
      - web-backend
    networks:
      - glossary-network

  autoscaling:
    build:
      context: ./autoscaling
    container_name: autoscaling
    depends_on:
      - ml-service
      - web-backend
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - glossary-network

networks:
  glossary-network:
    driver: bridge