version: "3.9"

services:
  web-backend:
    build:
      context: ./GlossaryKEKACHY/backend
    container_name: web-backend
    ports:
      - "8000:8000"
    environment:
      - PORT=8000

  ml-service:
    build:
      context: ./ml_service
    container_name: ml-service
    ports:
      - "9000:9000"
    depends_on:
      - web-backend

  web-frontend:
    build:
      context: ./GlossaryKEKACHY/frontend
    container_name: web-frontend
    environment:
      PORT: '8080'
      HOST: '0.0.0.0'
    ports:
      - "8080:8080"
    depends_on:
      - web-backend

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    ports:
      - "9090:9090"